#!/bin/python3

import gestalt

configfile = 'tests/config4tests.ini'


def test_loadConfig():
    settings = gestalt.LoadConfig(configfile)
    assert settings.protocol == 'http'
    assert settings.host == 'localhost'
    assert settings.port == '8080'
    assert settings.indexURL == 'http://localhost:8080/'
